name: "Build Python into exe"
on:
  pull_request:
    types:
      - closed

jobs:
  build-python:
    name: "Build exe"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: create executable
        run: |
          cd src
          pyinstaller -F main.py --name "PythonBlackjack"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: PythonBlackjack.exe
          path: /dist


